name: Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        linter: [
          {"name": "flake8", "format": "flake8", "cwd": ".", "cmd": "flake8 ."},
          {"name": "mypy", "format": "mypy", "cwd": ".", "cmd": "mypy ."},
          {"name": "pylint", "format": "pylint-json", "cwd": ".", "cmd": "pylint --load-plugins pylint_pytest $(Get-ChildItem -Filter *.py -Recurse .)"},
        ]
    name: ${{ matrix.linter.name }}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      uses: snok/install-poetry@v1
    - name: Install Python dependencies
      run: |
        poetry install
        poetry run python -m pip install git+https://github.com/bugale/Bugalintly.git@bugalintly
    - name: Lint
      run: |
        cd ${{ matrix.linter.cwd }}
        ${{ matrix.linter.cmd }} > lint.log
        $exitcode = $LASTEXITCODE
        type lint.log | poetry run Lintly --log --no-request-changes --no-review-body --base-dir . --format=${{ matrix.linter.format }} --comment-tag=${{ matrix.linter.name }}
        exit $exitcode
      env:
        LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
